{
  if (awaitCalled) {
    throw new IllegalStateException("await() already called");
  }
  awaitCalled=true;
  try {
    boolean ok=latch.await(delay,timeUnit);
    if (!ok) {
      throw new IllegalStateException("Timed out in waiting for test complete");
    }
 else {
      rethrowError();
    }
  }
 catch (  InterruptedException e) {
    throw new IllegalStateException("Test thread was interrupted!");
  }
}
