{
  checkThread();
  try {
    Assert.fail();
  }
 catch (  AssertionError e) {
    handleThrowable(e);
  }
}
