{
  try {
    Assert.assertFalse(condition);
  }
 catch (  AssertionError e) {
    handleThrowable(e);
  }
}
